#!/bin/sh
set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

paths=( "submodules/ios-store" "soomla-native/projects/cocos2dx-ios-store" )
build=../build/ios
build_headers=$build/headers

rm -rf $build
mkdir -p $build
mkdir -p $build_headers

for path in "${paths[@]}"
do
  $path/build_all
  cp -R $path/build/* $build/
done

cp -L submodules/ios-store/build/libSoomlaiOSStore.a $build/
cp -RL submodules/ios-store/build/headers/SoomlaiOSStore $build_headers/

cd - > /dev/null
