#!/bin/sh
set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

paths=( "submodules/android-store" "soomla-native/projects/cocos2dx-android-store" )
build=../build/android

rm -rf $build
mkdir -p $build

for path in "${paths[@]}"
do
  $path/build_all
  cp -R $path/build/* $build/
done

# handle special case of build_all location for android-store
cp -L submodules/android-store/build/AndroidStore.jar $build/
cp -R submodules/android-store/billing-services $build/

cd - > /dev/null
